export class DigitalSheet {
    constructor({ ATTRIBUTES, SKILLS, COUNTRIES, RACIAL_FEATURES, CLASSES, SPECIALIZATIONS, MUTANT_SUBTYPE_FEATURES, COLETES, INJURY_DESCRIPTIONS }) {
        this.ATTRIBUTES = ATTRIBUTES;
        this.SKILLS = SKILLS;
        this.COUNTRIES = COUNTRIES;
        this.RACIAL_FEATURES = RACIAL_FEATURES;
        this.CLASSES = CLASSES;
        this.SPECIALIZATIONS = SPECIALIZATIONS;
        this.MUTANT_SUBTYPE_FEATURES = MUTANT_SUBTYPE_FEATURES;
        this.COLETES = COLETES;
        this.INJURY_DESCRIPTIONS = INJURY_DESCRIPTIONS;
    }
} 