export const COLETES = {
	Nenhum: {
		ac: 10,
		addDex: true,
		maxDex: null,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 2,
		secondaryAmmo: 2,
	},
	"Roupa de Proteção": {
		ac: 11,
		addDex: true,
		maxDex: null,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 2,
		secondaryAmmo: 3,
	},
	"Colete Leve": {
		ac: 11,
		addDex: true,
		maxDex: null,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 2,
		secondaryAmmo: 3,
	},
	"Colete Alpha": {
		ac: 12,
		addDex: true,
		maxDex: null,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 3,
		secondaryAmmo: 3,
	},
	"Roupa reforçada": {
		ac: 12,
		addDex: true,
		maxDex: 2,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 3,
		secondaryAmmo: 4,
	},
	"Colete Medio": {
		ac: 13,
		addDex: true,
		maxDex: 2,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 4,
		secondaryAmmo: 4,
	},
	"Colete de placa": {
		ac: 14,
		addDex: true,
		maxDex: 2,
		strReq: 0,
		stealthDisadvantage: true,
		primaryAmmo: 5,
		secondaryAmmo: 4,
	},
	"Colete Tatico": {
		ac: 14,
		addDex: true,
		maxDex: 2,
		strReq: 0,
		stealthDisadvantage: false,
		primaryAmmo: 5,
		secondaryAmmo: 4,
	},
	"Colete Delta": {
		ac: 15,
		addDex: true,
		maxDex: 2,
		strReq: 0,
		stealthDisadvantage: true,
		primaryAmmo: 6,
		secondaryAmmo: 4,
	},
	"Colete reforçado": {
		ac: 15,
		addDex: false,
		maxDex: 0,
		strReq: 12,
		stealthDisadvantage: true,
		primaryAmmo: 7,
		secondaryAmmo: 4,
	},
	"Colete Pesado": {
		ac: 16,
		addDex: false,
		maxDex: 0,
		strReq: 13,
		stealthDisadvantage: true,
		primaryAmmo: 7,
		secondaryAmmo: 5,
	},
	Juggernaut: {
		ac: 17,
		addDex: false,
		maxDex: 0,
		strReq: 14,
		stealthDisadvantage: true,
		primaryAmmo: 8,
		secondaryAmmo: 5,
	},
	"Colete Omega": {
		ac: 18,
		addDex: false,
		maxDex: 0,
		strReq: 15,
		stealthDisadvantage: true,
		primaryAmmo: 8,
		secondaryAmmo: 5,
	},
};
