export const COUNTRIES = {
	AF: "Afeganistão",
	ZA: "África do Sul",
	AL: "Albânia",
	DE: "Alemanha",
	AD: "Andorra",
	AO: "Angola",
	SA: "Arábia Saudita",
	DZ: "Argélia",
	AR: "Argentina",
	AM: "Armênia",
	AU: "Austrália",
	AT: "Áustria",
	AZ: "Azerbaijão",
	BS: "Bahamas",
	BD: "Bangladesh",
	BB: "Barbados",
	BE: "Bélgica",
	BZ: "Belize",
	BJ: "Benin",
	BY: "Bielorrússia",
	BO: "Bolívia",
	BA: "Bósnia e Herzegovina",
	BW: "Botsuana",
	BR: "Brasil",
	BG: "Bulgária",
	BF: "Burkina Faso",
	BI: "Burundi",
	BT: "Butão",
	CV: "Cabo Verde",
	CM: "Camarões",
	KH: "Camboja",
	CA: "Canadá",
	QA: "Catar",
	KZ: "Cazaquistão",
	TD: "Chade",
	CL: "Chile",
	CN: "China",
	CY: "Chipre",
	CO: "Colômbia",
	CG: "Congo",
	CD: "Congo (RDC)",
	KR: "Coreia do Sul",
	CI: "Costa do Marfim",
	CR: "Costa Rica",
	HR: "Croácia",
	CU: "Cuba",
	DK: "Dinamarca",
	DJ: "Djibuti",
	DM: "Dominica",
	EG: "Egito",
	SV: "El Salvador",
	AE: "Emirados Árabes Unidos",
	EC: "Equador",
	SK: "Eslováquia",
	SI: "Eslovênia",
	ES: "Espanha",
	US: "Estados Unidos",
	EE: "Estônia",
	ET: "Etiópia",
	FJ: "Fiji",
	PH: "Filipinas",
	FI: "Finlândia",
	FR: "França",
	GA: "Gabão",
	GM: "Gâmbia",
	GH: "Gana",
	GE: "Geórgia",
	GR: "Grécia",
	GT: "Guatemala",
	GN: "Guiné",
	GW: "Guiné-Bissau",
	GQ: "Guiné Equatorial",
	GY: "Guiana",
	HT: "Haiti",
	NL: "Holanda",
	HN: "Honduras",
	HU: "Hungria",
	YE: "Iêmen",
	IN: "Índia",
	ID: "Indonésia",
	IQ: "Iraque",
	IR: "Irã",
	IE: "Irlanda",
	IS: "Islândia",
	IL: "Israel",
	IT: "Itália",
	JM: "Jamaica",
	JP: "Japão",
	JO: "Jordânia",
	KW: "Kuwait",
	LA: "Laos",
	LV: "Letônia",
	LB: "Líbano",
	LT: "Lituânia",
	LU: "Luxemburgo",
	MY: "Malásia",
	MW: "Malawi",
	MV: "Maldivas",
	ML: "Mali",
	MT: "Malta",
	MA: "Marrocos",
	MU: "Maurício",
	MR: "Mauritânia",
	MX: "México",
	MD: "Moldávia",
	MC: "Mônaco",
	MN: "Mongólia",
	ME: "Montenegro",
	MZ: "Moçambique",
	MM: "Mianmar",
	NP: "Nepal",
	NI: "Nicarágua",
	NE: "Níger",
	NG: "Nigéria",
	NO: "Noruega",
	NZ: "Nova Zelândia",
	OM: "Omã",
	PK: "Paquistão",
	PA: "Panamá",
	PY: "Paraguai",
	PE: "Peru",
	PL: "Polônia",
	PT: "Portugal",
	KE: "Quênia",
	GB: "Reino Unido",
	CZ: "República Tcheca",
	RO: "Romênia",
	RW: "Ruanda",
	RU: "Rússia",
	SN: "Senegal",
	SL: "Serra Leoa",
	RS: "Sérvia",
	SG: "Singapura",
	SY: "Síria",
	SO: "Somália",
	LK: "Sri Lanka",
	SE: "Suécia",
	CH: "Suíça",
	SR: "Suriname",
	TH: "Tailândia",
	TZ: "Tanzânia",
	TJ: "Tajiquistão",
	TG: "Togo",
	TT: "Trinidad e Tobago",
	TN: "Tunísia",
	TR: "Turquia",
	UA: "Ucrânia",
	UG: "Uganda",
	UY: "Uruguai",
	UZ: "Uzbequistão",
	VE: "Venezuela",
	VN: "Vietnã",
	ZM: "Zâmbia",
	ZW: "Zimbábue",
	OTHER: "Outro",
};
